# Generated by Django 3.0.3 on 2020-02-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
