# Generated by Django 3.0.3 on 2020-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_visitor_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
