# Generated by Django 3.0.3 on 2020-02-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0003_visitor_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
